title: mashmellow's blog
iconURL: assets/mash-icon.png
theme: jekyll-theme-leaf

# for a clean URL
permalink: :slug

social:
  twitter: its_mashmellow
  github: mashm3ll0w

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N