title: MashMellow's Blog
description: "Believing in my madness"
author:
  name: "mashmellow"
  email: "charlswall@live.com"
  url: "https://github.com/mashm3ll0w"

baseurl: /

source: .
destination: ./_site
permalink: /:title
paginate: 3
paginate_path: /page/:num/

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

future: true

remote_theme: pages-themes/hacker@v0.2.0
plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme

# Custom variables
owner : "mashmellow"
year : "2023"
